from building import *
import os

cwd = GetCurrentDir()

# 源文件必须使用相对路径，确保目标文件进入 VariantDir/build。
src = Glob('src/*.c')

# 头文件搜索路径可以使用绝对路径。
inc = [os.path.join(cwd, 'inc')]

if GetDepend('RADIOLIB_USING_SX1262'):
    src += Glob('modules/SX126x/*.c')
    inc.append(os.path.join(cwd, 'modules', 'SX126x'))

if GetDepend('RADIOLIB_USING_LR1121'):
    src += Glob('modules/LR11x0/*.c')
    inc.append(os.path.join(cwd, 'modules', 'LR11x0'))

if GetDepend('RADIOLIB_USING_LR2021'):
    src += Glob('modules/LR20xx/*.c')
    inc.append(os.path.join(cwd, 'modules', 'LR20xx'))

if GetDepend('RADIOLIB_USING_SX1276'):
    src += Glob('modules/SX127x/*.c')
    inc.append(os.path.join(cwd, 'modules', 'SX127x'))

if GetDepend('RADIOLIB_USING_SAMPLES'):
    src += Glob('samples/*.c')

group = DefineGroup(
    'RadioLib',
    src,
    depend=['PKG_USING_RADIOLIB'],
    CPPPATH=inc,
)

Return('group')