from building import *

cwd     = GetCurrentDir()
src     = Glob('aw86224.c')
if GetDepend('AW86224_USING_RT_DEVICE'):
    src += Glob('aw86224_rt_device.c')
inc = []

CPPPATH = [cwd]

inc += [cwd]

group = DefineGroup('AW86224', src, depend = ['PKG_USING_AW86224'], CPPPATH = inc)

Return('group')
