from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
inc = []

CPPPATH = [cwd]

inc += [cwd]

group = DefineGroup('AW86224', src, depend = ['PKG_USING_AW86224'], CPPPATH = inc)

Return('group')
