from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd + '/../../common', cwd]
group = DefineGroup('Drivers', src, depend = ['LCD_USING_CO5300_T_SF32'], CPPPATH = CPPPATH)

Return('group')
