from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
inc = []

CPPPATH = [cwd]

src += Glob('./src/*.c')

inc += [cwd + '/inc']

group = DefineGroup('XL9555', src, depend = ['PKG_USING_XL9555'], CPPPATH = inc)

Return('group')
