from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
inc = []

CPPPATH = [cwd]
inc += [cwd]

group = DefineGroup('UART_MANGER', src, depend = ['PKG_USING_UART_MANGER'], CPPPATH = inc)

Return('group')
