from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
inc = []

CPPPATH = [cwd]

inc += [cwd]

group = DefineGroup('tinygps', src, depend = ['PKG_USING_TINYGPS'], CPPPATH = inc)

Return('group')
