import os
from building import *

objs = []
cwd = GetCurrentDir()

for item in os.listdir(cwd):
    relative_script = os.path.join(item, 'SConscript')
    source_script = os.path.join(cwd, relative_script)

    if os.path.isfile(source_script):
        objs += SConscript(relative_script)

Return('objs')