import os
from building import *

objs = []
cwd = GetCurrentDir()

for item in os.listdir(cwd):
    script = os.path.join(cwd, item, 'SConscript')
    if os.path.isfile(script):
        objs += SConscript(script)

Return('objs')
