from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
inc = []

CPPPATH = [cwd]

inc += [cwd]

group = DefineGroup('ADS1115', src, depend = ['PKG_USING_ADS1115'], CPPPATH = inc)

Return('group')
