from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')
path =  [cwd, 
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_T_DISPLAY_SF32'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_T_DISPLAY_SF32'):
    group = group + SConscript('../t-display-sf32-base/script/SConscript')

Return('group')
