from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
inc = []

CPPPATH = [cwd]

src += Glob('./src/*.c')

if not GetDepend('BHI260AP_USING_RT_SENSOR'):
    src = [item for item in src if not str(item).endswith('bhi260ap_rt_sensor.c')]

inc += [cwd + '/inc']

inc += [cwd + '/firmware']
inc += [cwd + '/firmware/bhi260ap']
inc += [cwd + '/firmware/bhi260ap_klio']
inc += [cwd + '/firmware/bhi260ap_swim']

group = DefineGroup('BHI260AP', src, depend = ['PKG_USING_BHI260AP'], CPPPATH = inc)

Return('group')
