from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
inc = []

CPPPATH = [cwd]
inc += [cwd]

group = DefineGroup('AUDIO_MANGER', src, depend = ['PKG_USING_AUDIO_MANAGER_LIB'], CPPPATH = inc)

Return('group')
